version: '3.9'

services:
  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend/data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend
    ports:
      - "3000:3000"  
    restart: unless-stopped
